---
title: "Surface Water"
author: "Michael Rustler"
date: "`r Sys.time()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Surface Water}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Daily Surface Water Data

By running the code below all available `daily surface water` data of monitoring 
stations from Wasserportal Berlin will be downloaded and exported into one `.json`
file for each parameter and all available monitoring stations.


```{r surface_data_daily_export}
library(wasserportal)

stations <- wasserportal::get_stations()
variables <- wasserportal::get_surfacewater_variables()

sw_data_daily_list <- wasserportal::get_daily_surfacewater_data(stations,
                                                          variables)

sw_data_to_csv <- function(sw_data_daily_list) {
tmp <- lapply(seq_len(length(sw_data_daily_list)), function(i) {
  filename <- sprintf("daily_%s.csv", names(sw_data_daily_list[i]))
  msg <- sprintf("Writting '%s'", filename)
                                                                          
  kwb.utils::catAndRun(messageText = msg,
                       expr = {
  readr::write_csv(sw_data_daily_list[[i]],
                   file = filename)
                       })
  filename
})

unlist(tmp)

}

files <- sw_data_to_csv(sw_data_daily_list)

# Data availability per parameter
sw_data_daily_list %>%
  dplyr::bind_rows() %>% 
  dplyr::count(Parameter, Einheit)

```
The following `.csv` files are available for download: 

```{r daily_surface_water_data_csv, echo = FALSE, results ='asis'}


cat(paste0(sprintf("- [%s](https://kwb-r.github.io/wasserportal/%s)", 
        files, 
        files),
       collapse = "\n\n"))

```




## Daily Surface Water Levels


```{r surface_waterlevel}

swl_master <- wasserportal::get_wasserportal_masters_data(
  station_ids = stations$overview_list$surface_water.water_level %>%
    dplyr::filter(.data$Betreiber == "Land Berlin") %>%
    dplyr::pull(.data$Messstellennummer)
)

swl_data <- sw_data_daily_list$surface_water.water_level %>% 
  dplyr::select(where(~!all(is.na(.x)))) %>%
  dplyr::left_join(swl_master[, c("Nummer", "Pegelnullpunkt_m")],
                   by = c("Messstellennummer" = "Nummer")) %>%
  dplyr::mutate(Tagesmittelwert_Pegelstand_mNN = as.numeric(.data$Pegelnullpunkt_m) + .data$Tagesmittelwert/100) %>%
  ### remove -777 for messstellennummer 5867000 (few values in 2000) resulted by step above
  dplyr::filter(.data$Tagesmittelwert_Pegelstand_mNN != -777) %>%
  dplyr::select(- .data$Pegelnullpunkt_m)

```
