---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
is_ghactions <- identical(Sys.getenv("CI"), "true")
```

## Stations

### General overview



```{r stations_overview}
# install.packages("remotes")
# remotes::install_github("kwb-r/wasserportal", upgrade = "never", force = TRUE)

overview_options <- wasserportal::get_overview_options()
str(overview_options)

system.time(stations <- wasserportal::get_stations())

str(stations)

DT::datatable(stations$crosstable, filter = "top", caption = "Data availabilty 
              per monitoring station")

jsonlite::write_json(stations$crosstable, 
                     path = "stations_crosstable.json",
                     pretty = TRUE)
```
```{r input_ghactions0, echo=FALSE, results='asis', eval=is_ghactions}
cat("The crosstable data for checking data availabilty of the monitoring stations 
is also available in JSON format here:
[https://kwb-r.github.io/wasserportal/stations_crosstable.json](../stations_crosstable.json)
")
```

### GW level

Master data of GW level stations can be requested as shown below:

```{r stations_gwl}

DT::datatable(stations$overview_list$groundwater.level, filter = "top")

### Plot GW level classification (provided by SenWeb)
g1 <- ggplot2::ggplot(stations$overview_list$groundwater.level, 
                      ggplot2::aes_string(x = "Klassifikation")) +
ggplot2::geom_bar() + 
ggplot2::labs(title = "GW level classification (SenWeb)") +
ggplot2::theme_bw() 

plotly::ggplotly(g1)

stations_gwl_master <- wasserportal::get_wasserportal_masters_data(
  station_ids = stations$overview_list$groundwater.level$Messstellennummer
)

DT::datatable(stations_gwl_master, filter = "top")

jsonlite::write_json(stations_gwl_master, 
                     path = "stations_gwl_master.json",
                     pretty = TRUE)

``` 

```{r input_ghactions1, echo=FALSE, results='asis', eval=is_ghactions}
cat("The master data of GW level stations is also available in JSON format here:
[https://kwb-r.github.io/wasserportal/stations_gwl_master.json](../stations_gwl_master.json)
")
```

#### Download and Plotting 

for total period available.

```{r test_gwl_download}
station_gwl <- stations$overview_list$groundwater.level[1,]
ncols <- 2:ncol(station_gwl)

gw_level <- wasserportal::read_wasserportal_raw_gw(
  station = station_gwl$Messstellennummer, 
  stype = "gwl")
gw_level$Datum <- as.Date(gw_level$Datum, format = "%d.%m.%Y")
names(gw_level) <- kwb.utils::substSpecialChars(names(gw_level))
head(gw_level)

g <- ggplot2::ggplot(gw_level, ggplot2::aes_string(x = "Datum", y = "GW_Stand_m_ue_NHN")) +
ggplot2::geom_line() +
ggplot2::geom_point() +
ggplot2::theme_bw()


title_subtitle <- paste0(paste0(names(station_gwl)[1], ": ", 
                             station_gwl[1], 
                             collapse =", "),
       "<br>",
       "<sup>",
       paste0(names(station_gwl)[ncols], ": ",
              station_gwl[ncols], 
              collapse =", "),
       "</sup>")


plotly::ggplotly(g) %>%
  plotly::layout(title = list(text = title_subtitle))
```

### GW quality

Master data of GW quality stations can be requested as shown below:

```{r stations_gwq}
stations_gwq <- wasserportal::get_wasserportal_stations_table(
  type = overview_options$groundwater$quality
  )

DT::datatable(stations_gwq, filter = "top")


stations_gwq_master <- wasserportal::get_wasserportal_masters_data(
  station_ids = stations_gwq$Messstellennummer
)

DT::datatable(stations_gwq_master, filter = "top")

jsonlite::write_json(stations_gwq_master, 
                     path = "stations_gwq_master.json",
                     pretty = TRUE)

``` 

```{r input_ghactions2, echo=FALSE, results='asis', eval=is_ghactions}
cat("The master data of GW quality stations is also available in JSON format here:
[https://kwb-r.github.io/wasserportal/stations_gwq_master.json](../stations_gwq_master.json)
")
```

#### Download and Plotting 

Not implemented yet !!!
