#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:31.576169.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("warning_not_implemented() works", {

  expect_error(
    wasserportal:::warning_not_implemented()
    # argument "x" is missing, with no default
  )

})

