#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:09:38.376262.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_groundwater_data() works", {

  f <- wasserportal:::get_groundwater_data

  expect_error(f(debug = FALSE))

  stations <- list(
    overview_list = list(
      groundwater.level = data.frame(
        Messstellennummer = 3
      ),
      groundwater.quality = data.frame(
        Messstellennummer = 3
      )
    )
  )

  result <- f(stations, debug = FALSE)

  expect_length(result, 2L)
  expect_type(result, "list")

  expect_true(all(
    sapply(result, kwb.utils::mainClass) == "data.table"
  ))

})
