#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:01.710311.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_stations() works", {

  expect_output(result <- wasserportal:::get_stations())

  expect_identical(
    names(result),
    c("overview_list", "overview_df", "crosstable")
  )
})
