#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:09:31.879282.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("sw_data_list_to_df() works", {

  expect_error(
    wasserportal:::sw_data_list_to_df()
    # argument "sw_data_list" is missing, with no default
  )

})

