#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:17.601624.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("to_base_filename() works", {

  expect_error(
    wasserportal:::to_base_filename()
    # argument "x" is missing, with no default
  )

})

