#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:46.168353.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("base_url_download() works", {

  result <- wasserportal:::base_url_download()

  expect_length(result, 1L)
  expect_type(result, "character")
  expect_true(startsWith(result, "https://"))
})

