#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:44.744923.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("readPackageFile() works", {

  expect_error(
    wasserportal:::readPackageFile()
    # argument "file" is missing, with no default
  )

})

