#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:19.218318.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("list_timeseries_data_to_zip() works", {

  expect_error(
    wasserportal:::list_timeseries_data_to_zip()
    # argument "timeseries_data_list" is missing, with no default
  )

})

