#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:09:41.860028.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_station_variables() works", {

  expect_error(
    wasserportal:::get_station_variables()
    # argument "station_df" is missing, with no default
  )

})

