#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:09:38.527944.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_overview_options() works", {

  result <- wasserportal:::get_overview_options()

  expect_identical(
    names(result),
    c("surface_water", "groundwater")
  )

  expect_true(all(sapply(result, is.list)))
})
