#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:57.965598.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("wp_masters_data_to_list() works", {

  expect_error(
    wasserportal:::wp_masters_data_to_list()
    # argument "overview_list_names" is missing, with no default
  )

})

