#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:44.744923.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("read() works", {

  f <- wasserportal:::read

  expect_identical(f(), NULL)

  expect_identical(
    f(c("a;b", "1;2,3"), header = TRUE),
    data.frame(a = 1L, b = 2.3)
  )
})
