#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:16.872839.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("get_wasserportal_variables() works", {

  result <- wasserportal:::get_wasserportal_variables()

  expect_type(result, "character")
  expect_true("Wassertemperatur" %in% names(result))
})
