#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:18.525365.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("list_masters_data_to_csv() works", {

  expect_error(
    wasserportal:::list_masters_data_to_csv()
    # argument "masters_data_list" is missing, with no default
  )

})

