#
# This test file has been generated by kwb.test::create_test_files()
# launched by user hsonne on 2023-09-23 23:10:17.601624.
# Your are strongly encouraged to modify the dummy functions
# so that real cases are tested. You should then delete this comment.
#

test_that("wasserportal_base_url() works", {

  result <- wasserportal:::wasserportal_base_url()

  expect_type(result, "character")
  expect_length(result, 1L)
  expect_true(startsWith(result, "https://"))

})
