on:
  push:
    branches:
      - main
      - master
      - dev
  schedule:
    # This is a change just to trigger a rerun!
    # * is a special character in YAML so you have to quote this string ()
    # Run this job every day at 05:00 a.m UTC ('0 5 * * *')
    - cron:  '0 5 * * *'

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ZENODO_PAT: ${{ secrets.ZENODO_PAT }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, github::kwb-r/kwb.pkgbuild
          needs: website

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'kwb.pkgbuild::deploy_to_branch_with_extra_files(vignettes_file_pattern_to_copy = "\\\.json$|\\\.csv$|\\\.html$|\\\.zip$")'
